config/routes.rb
Nanomedtrix::Application.routes.draw do
  mount Spree::Core::Engine, at: '/'

  Spree::Core::Engine.routes.draw do
		namespace :admin do
			resources :articles
			resource  :banner_settings
			
			resources :products do 
				resources :documents do 
					collection do 
						post :update_positions
					end
				end
			end

			resources :banners do
      	collection do
        	post :update_positions
      	end
      
      	member do
        	get :clone
      	end
    	end
		end

		resources :articles

		match '/news',                       to: 'articles#index',    via: 'get', as: :news
		match '/news/feed',                  to: 'articles#feed',     via: 'get', as: :news_feed, format: :rss
		match '/news/tag/:tag',              to: 'articles#tag',      via: 'get', as: :news_tag
		match '/news/article/:slug',         to: 'articles#show',     via: 'get', as: :article_permalink
		match '/news/author/:author',        to: 'articles#author',   via: 'get', as: :news_author
		match '/news/category/:category',    to: 'articles#category', via: 'get', as: :news_category
		match '/news/:year(/:month)(/:day)', to: 'articles#archive',  via: 'get', as: :news_archive, constraints: {
																																																	 year:  /(19|20)\d{2}/, 
																																																	 month: /[01]?\d/, 
																																																	 day:   /[0-3]?\d/
																																																 }
	end
end

app/models/spree/app_configuration_decorator.rb
Spree::AppConfiguration.class_eval do
	preference :banner_default_url,        :string, default: '/assets/banners/:id/:style/:basename.:extension'
	preference :banner_path,               :string, default: ':rails_root/public/assets/banners/:id/:style/:basename.:extension'
	preference :banner_url,                :string, default: '/assets/banners/:id/:style/:basename.:extension'
	preference :banner_styles,             :string, default: "{ \"mini\": \"48x48#\", \"home_carousel\": \"800x450>\", \"featured_small\": \"270x240#\", \"featured_wide\": \"560x130#\", \"featured_large\": \"560x390#\" }"
	preference :banner_default_categories, :string, default: "{ \"logo\": \"Logo\", \"home_carousel\": \"Home Page Carousel\", \"products_featured\": \"Featured Products\" }"
end

app/models/spree/article.rb
require 'acts-as-taggable-on'

class Spree::Article < ActiveRecord::Base
  before_save :create_permalink
  before_save :set_published_at

  validates :title, presence: true
  validates :body,  presence: true
  
  default_scope   -> { order( 'published_at DESC' ) }
  scope :visible, -> { where( visible: true ) }
  scope :recent,  lambda { | max = 5 | visible.limit( max ) }

  if Spree.user_class
    belongs_to :author, class_name: Spree.user_class.to_s
  else
    belongs_to :author
  end

  has_one :article_image, as: :viewable, dependent: :destroy, class_name: 'Spree::ArticleImage'

  accepts_nested_attributes_for :article_image, reject_if: :all_blank
  acts_as_taggable_on           :tags, 
                                :categories

  def article_summary( chars = 200 )
    if summary.blank?
      "#{ body[ 0...chars ] }..."
    else
      summary
    end
  end

  def self.by_date( date, period = nil )
    if date.is_a?( Hash )
      keys   = [ :day, :month, :year ].select { | key | date.include?( key ) }
      period = keys.first.to_s
      date   = DateTime.new( *keys.reverse.map { | key | date[ key ].to_i } )
    end

    time = date.to_time.in_time_zone
    where( published_at: ( time.send( "beginning_of_#{ period }" )..time.send( "end_of_#{ period }" ) ) )
  end 

  def self.by_tag( tag_name )
    tagged_with( tag_name, on: :tags )
  end

  def self.by_category( category_name )
    tagged_with( category_name, on: :categories )
  end

  def self.by_author( author )
    where( author_id: author )
  end

  # data for news archive widget, only visible entries
  def self.organize_articles
    Hash.new.tap do | articles |
      years.each do | year |
        months_for( year ).each do | month |
          date = DateTime.new( year, month )

          articles[ year ] ||= []
          articles[ year ] << [ date.strftime( "%B" ), self.visible.by_date( date, :month ) ]
        end
      end
    end
  end

  private

  def self.years
    visible.all.map { | e | e.published_at.year }.uniq
  end

  def self.months_for( year )
    visible.all.select { | e | e.published_at.year == year }.map { | e | e.published_at.month }.uniq
  end

  def create_permalink
    self.permalink = title.to_url if permalink.blank?
  end

  def set_published_at
    self.published_at = Time.now if published_at.blank?
  end

  def validate
    # nicEdit field contains "<br>" when blank
    errors.add( :body, "can't be blank" ) if body =~ /^<br>$/
  end
end 

app/models/spree/article_image.rb
class Spree::ArticleImage < Spree::Image
  has_attached_file :attachment, 
    									styles: { 
    										mini:   '48x48#', 
    										normal: '200x200>', 
    										large:  '600x600>'
    									},
     									default_style: :large,
     									url:  "/assets/article_images/:id/:style/:basename.:extension",
     									path: ":rails_root/public/assets/article_images/:id/:style/:basename.:extension"  
end

app/models/spree/banner_configuration.rb
module Spree
  class BannerConfiguration < Preferences::Configuration
    preference :banner_default_url,   :string, default: '/assets/banners/:id/:style/:basename.:extension'
    preference :banner_path,          :string, default: ':rails_root/public/assets/banners/:id/:style/:basename.:extension'
    preference :banner_url,           :string, default: '/assets/banners/:id/:style/:basename.:extension'
    preference :banner_styles,        :string, default: "{ \"mini\": \"48x48>\", \"small\": \"100x100>\", \"large\": \"800x200#\" }"
    preference :banner_default_style, :string, default: 'small'
  end
end

app/models/spree/document.rb
module Spree
  class Document < Asset
    ALLOWED_CONTENT_TYPES   = [ 'application/msword', 'application/vnd.ms-excel', 'application/pdf' ]
    ALLOWED_FILE_EXTENSIONS = [ 'pdf', 'doc', 'docx', 'xls', 'xlsx' ]

    validate :no_attachment_errors

    has_attached_file :attachment,
                      url:  "/assets/product/documents/:id/:style/:basename.:extension",
                      path: ":rails_root/public/assets/product/documents/:id/:style/:basename.:extension"

    before_post_process :skip_thumbnail_creation

    def no_attachment_errors
      unless attachment.errors.empty?
        # uncomment this to get rid of the less-than-useful interrim messages
        # errors.clear 
        errors.add :attachment, "Paperclip returned errors for file '#{ attachment_file_name }' - check document source file."
        false
      end
    end

    private
      def skip_thumbnail_creation
        return false if ( attachment_content_type =~ /application\/.*pdf/ or ALLOWED_CONTENT_TYPES.include?( attachment_content_type ) )
      end
  end
end

app/models/spree/user_decorator.rb
if Spree.user_class
  Spree.user_class.class_eval do
    has_many :news_articles, foreign_key: :author_id
  end
end

app/controllers/spree/admin/articles_controller.rb
class Spree::Admin::ArticlesController < Spree::Admin::ResourceController
  helper 'spree/articles'

  private
    def location_after_save
      edit_admin_article_url( @article )
    end

    def collection
      page     = params[ :page ].to_i     > 0 ? params[ :page ].to_i     : 1
      per_page = params[ :per_page ].to_i > 0 ? params[ :per_page ].to_i : 20

      model_class.scoped.page( page ).per( per_page )
    end

    def spree_articles_params
      params.require( :spree_articles ).permit( Spree::PermittedAttributes.article_attributes.push :author_id, 
                                                                                                   :title, 
                                                                                                   :summary, 
                                                                                                   :body, 
                                                                                                   :permalink, 
                                                                                                   :visible, 
                                                                                                   :published_at, 
                                                                                                   :tag_list, 
                                                                                                   :category_list, 
                                                                                                   :article_image, 
                                                                                                   :article_image_attributes 
      )
    end
end

app/controllers/spree/admin/banner_settings_controller.rb
module Spree
  module Admin
    class BannerSettingsController < Spree::Admin::BaseController
      def edit
        @styles  = ActiveSupport::JSON.decode( Spree::Config[ :banner_styles ] )
      end

      def update
        update_styles( params )

        Spree::Config.set( params[ :preferences ] )
        update_paperclip_settings

        respond_to do | format |
          format.html {
            flash[ :notice ] = Spree.t( :banner_settings_updated )
            redirect_to edit_admin_banner_settings_path
          }
        end
      end

      private
        def update_styles params
          params[ :new_banner_styles ].each do | index, style |
            params[ :banner_styles ][ style[ :name ] ] = style[ :value ] unless style[ :value ].empty?
          end if params[ :new_banner_styles ].present?

          styles = params[ :banner_styles ]

          Spree::Config[ :banner_styles ] = ActiveSupport::JSON.encode( styles ) unless styles.nil?
        end

        def update_paperclip_settings
          Spree::Banner.attachment_definitions[ :attachment ][ :styles ]        = ActiveSupport::JSON.decode( Spree::Config[ :banner_styles ] ).symbolize_keys!
          Spree::Banner.attachment_definitions[ :attachment ][ :path ]          = Spree::Config[ :banner_path ]
          Spree::Banner.attachment_definitions[ :attachment ][ :default_url ]   = Spree::Config[ :banner_default_url ]
          Spree::Banner.attachment_definitions[ :attachment ][ :default_style ] = Spree::Config[ :banner_default_style ]
        end
    end
  end
end

app/controllers/spree/admin/banners_controller.rb
module Spree
  module Admin
    class BannersController < ResourceController
      before_filter :load_categories
      create.before :update_position
      helper_method :clone_object_url
      
      def index
        session[ :return_to ] = request.url

        @collection
      end

      def show
        session[ :return_to ] ||= request.referer

        redirect_to action: :edit
      end

      def update
        @banner.enhance_settings
        
        super
      end

      def clone
        @new = @banner.duplicate

        if @new.save
          flash.notice = Spree.t( 'notice_messages.banner_cloned' )
        else
          flash.notice = Spree.t( 'notice_messages.banner_not_cloned')
        end

        respond_with( @new ) { | format | format.html { redirect_to edit_admin_banner_url( @new ) } }
      end

      private
        def find_resource
          Banner.find( params[ :id ] )
        end

        def load_categories
          @categories = Spree::Banner.categories
        end

        def location_after_save
          edit_admin_banner_url( @banner )
        end

        def update_position
          c = params[ :banner ][ :category ]
          p = Spree::Banner.with_category( c ).last.position + 1

          params[ :banner ][ :position ] = p 
        end

        def collection
          @collection = {}

          params[ :q ]       ||= {}
          params[ :q ][ :s ] ||= 'position asc'
          
          Spree::Banner.categories.each do | key, value |
            params[ :q ][ :category_eq ] = key

            @search            = super.ransack( params[ :q ] )
            @collection[ key ] = @search.result
          end

          @collection
        end
        
        def clone_object_url resource
          clone_admin_banner_url resource
        end

        def spree_banners_params
          params.require( :spree_banners ).permit( Spree::PermittedAttributes.banner_attributes.push :caption,
                                                                                                     :alt_text, 
                                                                                                     :url,
                                                                                                     :category,
                                                                                                     :position,
                                                                                                     :enabled,
                                                                                                     :attachment
          )
        end
    end
  end
end

app/controllers/spree/admin/documents_controller.rb
module Spree
  module Admin
    class DocumentsController < ResourceController
      helper 'spree/admin/images'
      
      before_filter :load_data

      create.before :set_viewable
      update.before :set_viewable
      destroy.before :destroy_before

      private
        def location_after_save
          admin_product_documents_url( @product )
        end

        def load_data
          @product  = Spree::Product.where( permalink: params[ :product_id ] ).first
          @variants = @product.variants.collect do | variant |
            [ variant.options_text, variant.id ]
          end

          @variants.insert( 0, [ Spree.t( :all ), @product.master.id ] )
        end

        def set_viewable
          @document.viewable_type = 'Spree::Variant'
          @document.viewable_id   = params[ :document ][ :viewable_id ]
        end

        def destroy_before
          @viewable = @document.viewable
        end

        def spree_documents_params
          params.require( :spree_documents ).permit( Spree::PermittedAttributes.document_attributes.push :alt, 
                                                                                                         :attachment, 
                                                                                                         :position, 
                                                                                                         :viewable_type, 
                                                                                                         :viewable_id 
          )
        end
    end
  end
end

app/controllers/spree/admin/product_documents_controller.rb
module Spree
  module Admin
    class DocumentsController < ResourceController
      before_filter :load_data

      create.before :set_viewable
      update.before :set_viewable
      destroy.before :destroy_before

      private
        def location_after_save
          admin_product_documents_url( @product )
        end

        def load_data
          @product  = Spree::Product.where( permalin: params[ :product_id ] ).first
          @variants = @product.variants.collect do | variant |
            [ variant.options_text, variant.id ]
          end

          @variants.insert( 0, [ I18n.t( :all ), @product.master.id ] )
        end

        def set_viewable
          @document.viewable_type = 'Spree::Variant'
          @document.viewable_id   = params[ :document ][ :viewable_id ]
        end

        def destroy_before
          @viewable = @document.viewable
        end
    end
  end
end

app/controllers/spree/admin/products_controller_decorator.rb
# Make the Doc Helper available to all views
Spree::Admin::ProductsController.class_eval do
    helper 'spree/admin/product_documents'
end

app/controllers/spree/articles_controller.rb
class Spree::ArticlesController < Spree::StoreController
  helper 'spree/articles' 

  before_filter :init_pagination, only: [ :index, :tag, :archive, :author, :category ]
  rescue_from   ActiveRecord::RecordNotFound, with: :render_404
  
  def index
    @articles = Spree::Article.visible.page( @pagination_page ).per( @pagination_per_page )
  end
  
  def show
    if try_spree_current_user.try( :has_spree_role?, 'admin' )
      @article = Spree::Article.find_by_permalink!( params[ :slug ] )
    else
      @article = Spree::Article.visible.find_by_permalink!( params[ :slug ] )
    end

    @title = @article.title
  end

  def tag
    @articles = Spree::Article.visible.by_tag( params[ :tag ] ).page( @pagination_page ).per( @pagination_per_page )
    @tag_name = params[ :tag ]
  end

  def category
    @articles      = Spree::Article.visible.by_category( params[ :category ] ).page( @pagination_page ).per( @pagination_per_page )
    @category_name = params[ :category ]
  end

  def archive
    @articles = Spree::Article.visible.by_date( params ).page( @pagination_page ).per( @pagination_per_page )
  end
  
  def feed
    @articles = Spree::Article.visible.limit( 20 )

    render layout: false
  end

  def author
    @author   = Spree.user_class.where( email: params[ :author ] ).first
    @articles = Spree::Article.visible.by_author( @author ).page( @pagination_page ).per( @pagination_per_page )
  end

  private
    def init_pagination
      @pagination_page     = params[ :page ].to_i     > 0 ? params[ :page ].to_i     : 1
      @pagination_per_page = params[ :per_page ].to_i > 0 ? params[ :per_page ].to_i : 10
    end
end

app/views/spree/articles/_article.html.erb
<%= link_to article_permalink( article ), class: 'list-group-item' do %>
	<h4 class="list-grou-item-heading">
		<%= article.title %>
		<small><%= render partial: 'spree/articles/article_details', locals: { article: article } %></small>
	</h4>

	<p class="list-group-item-text">
  	<%== article.article_summary %>
  </p>
<% end %>

app/views/spree/articles/_article_details.html.erb
<div class="article_details">
  <%= Spree.t( :posted_on ) %> <span class="article_date"><%= l( article.published_at, format: :news_date ) %></span>

  <% unless article.author.blank? %>
    <%= Spree.t( :by ) %> <%= link_to article.author.email, '#', class: 'article_author' %>
  <% end %>.

  <% unless article.category_list.empty? %>
    <%= Spree.t( :posted_in ) %> <%= article_category_list_html article %>.
  <% end %>

  <% unless article.tag_list.empty? %>
    <%= Spree.t( :tagged ) %> <%= article_tag_list_html article %>.
  <% end %>
</div>

app/views/spree/articles/_articles.html.erb
<div class="list-group">
  <% if !@articles.empty? %>
    <% @articles.each do | article | %>
      <%= render partial: 'spree/articles/article', locals: { article: article } %>
    <% end %>

    <%= paginate @articles %>
  <% else %>
    <p class="lead" id="no_entries"><%= Spree.t( :no_articles ) %></p>
  <% end %>
</div>  

app/views/spree/articles/_categories_list.html.erb
<ul class="news_categories_list">
  <% Spree::Article.visible.tag_counts_on( :categories ).sort_by( &:count ).reverse.each do | category | %>
    <li><%= link_to category.name, news_category_path( category.name ) %> (<%= category.count %>)</li>
  <% end %>
</ul>

app/views/spree/articles/_headlines.html.erb
<div id="news-headlines" class="well well-sm">
	<dl class="dl-horizontal">
		<dt>News Headlines</dt>

		<dd>
			<div id="news-headlines-carousel" class="carousel" data-ride="carousel" data-interval="2000">
				<div class="carousel-inner">
					<div class="item active">
						<%= link_to first_headline.title, article_permalink( first_headline ) %>
					</div>

					<% headlines.each do | article | %>
						<div class="item">
							<%= link_to article.title, article_permalink( article ) %>
						</div>
					<% end %>
				</div>
			</div>
		</dd>
	</dl>
</div>

app/views/spree/articles/_recent_articles.html.erb
<ul class="recent_articles">
  <% recent_articles.each do | article | %>
    <li>
      <%= link_to article_permalink( article ) do %>
        <%= article.title %>

        <span class="article-date"><%= "#{ time_ago_in_words article.published_at } ago" %></span> 
      <% end %>
    </li>
  <% end %>
</ul>

app/views/spree/articles/_sidebar_index.html.erb
<div id="article_sidebar">
  <h6>News Categories</h6>
  <%= render partial: 'spree/articles/categories_list' %>

  <h6>News Tag Cloud</h6>
  <%= render partial: 'spree/articles/tag_cloud' %>
  
  <h6>Recent Articles</h6>
  <%= render partial: 'spree/articles/recent_articles', object: Spree::Article.recent( 10 ) %>

  <h6>News Archive</h6>
  <%= render partial: 'spree/articles/news_archive', object: Spree::Article.organize_articles %>
</div>

app/views/spree/articles/_sidebar_show.html.erb
<div id="article_sidebar">
  <h6>News Categories</h6>
  <%= render partial: 'spree/articles/categories_list' %>

  <h6>News Tag Cloud</h6>
  <%= render partial: 'spree/articles/tag_cloud' %>

  <h6>Recent Articles</h6>
  <%= render partial: 'spree/articles/recent_articles', object: Spree::Article.recent( 10 ) %>

  <h6>News Archive</h6>
  <%= render partial: 'spree/articles/news_archive', object: Spree::Article.organize_articles %>
</div>

app/views/spree/articles/_tag_cloud.html.erb
<ul class="blog_tag_cloud">
  <% tag_cloud( Spree::Article.visible.tag_counts_on( :tags ), %w( css1 css2 css3 css4 ) ) do | tag, css_class | %>
    <li><%= link_to tag.name, news_tag_path( tag.name ), class: css_class %></li>
  <% end %>
</ul>

app/views/spree/articles/archive.html.erb
<% content_for :sidebar do %>
  <%= render partial: 'spree/articles/sidebar_index' %>
<% end %>

<h1>
	<%= Spree.t( :news_archive ) %>: <%= t( 'date.month_names' )[params[ :month ].to_i ] unless params[ :month ].blank? %> <%= params[ :year ].to_i %>
</h1>

<%= render partial: 'spree/articles/articles' %>

app/views/spree/articles/author.html.erb
<% content_for :sidebar do %>
  <%= render partial: 'spree/articles/sidebar_index' %>
<% end %>

<div class="columns twelve alpha omega article_author_info">
  <div class="columns six alpha">
    <h1><%= "#{ t :article_author }: #{ @author.email }" %></h1>
  </div>
</div>

<%= render partial: 'spree/articles/articles' %>

app/views/spree/articles/category.html.erb
<% content_for :sidebar do %>
  <%= render partial: 'spree/articles/sidebar_index' %>
<% end %>

<h1><%= Spree.t( :news_category ) %>: <%= @category_name %></h1>

<%= render partial: 'spree/articles/articles' %>

app/views/spree/articles/show.html.erb
<% @body_id = 'news' %>

<div id="col-left" class="col-sm-4">
	<div class="page-header">
		<h4><%= Spree.t( :news ) %></h4>
	</div>

	<div class="col-content">
  	<%= render partial: 'spree/articles/sidebar_show' %>
  </div>
</div>

<div id="col-right" class="col-sm-8">
  <div class="page-header">
    <h4><%= @article.title %></h4>
  </div>

  <div class="col-content">
  	<%== @article.body %>

    <%= render partial: 'spree/articles/article_details', locals: { article: @article } %>
  </div>
</div> 

app/views/spree/articles/tag.html.erb
<% content_for :sidebar do %>
  <%= render partial: 'spree/articles/sidebar_index' %>
<% end %>

<h1><%= Spree.t( :news_tag ) %>: <%= @tag_name %></h1>

<%= render partial: 'spree/articles/news_articles' %>