config/routes.rb
Nanomedtrix::Application.routes.draw do
  mount Spree::Core::Engine, at: '/'

  Spree::Core::Engine.routes.draw do
		namespace :admin do
			resources :articles
			resource  :banner_settings
			
			resources :products do 
				resources :documents do 
					collection do 
						post :update_positions
					end
				end
			end

			resources :banners do
      	collection do
        	post :update_positions
      	end
      
      	member do
        	get :clone
      	end
    	end
		end

		resources :articles

		match '/news',                       to: 'articles#index',    via: 'get', as: :news
		match '/news/feed',                  to: 'articles#feed',     via: 'get', as: :news_feed, format: :rss
		match '/news/tag/:tag',              to: 'articles#tag',      via: 'get', as: :news_tag
		match '/news/article/:slug',         to: 'articles#show',     via: 'get', as: :article_permalink
		match '/news/author/:author',        to: 'articles#author',   via: 'get', as: :news_author
		match '/news/category/:category',    to: 'articles#category', via: 'get', as: :news_category
		match '/news/:year(/:month)(/:day)', to: 'articles#archive',  via: 'get', as: :news_archive, constraints: {
																																																	 year:  /(19|20)\d{2}/, 
																																																	 month: /[01]?\d/, 
																																																	 day:   /[0-3]?\d/
																																																 }
	end
end

app/controllers/spree/admin/banner_settings_controller.rb
module Spree
  module Admin
    class BannerSettingsController < Spree::Admin::BaseController
      def edit
        @styles  = ActiveSupport::JSON.decode( Spree::Config[ :banner_styles ] )
      end

      def update
        update_styles( params )

        Spree::Config.set( params[ :preferences ] )
        update_paperclip_settings

        respond_to do | format |
          format.html {
            flash[ :notice ] = Spree.t( :banner_settings_updated )
            redirect_to edit_admin_banner_settings_path
          }
        end
      end

      private
        def update_styles params
          params[ :new_banner_styles ].each do | index, style |
            params[ :banner_styles ][ style[ :name ] ] = style[ :value ] unless style[ :value ].empty?
          end if params[ :new_banner_styles ].present?

          styles = params[ :banner_styles ]

          Spree::Config[ :banner_styles ] = ActiveSupport::JSON.encode( styles ) unless styles.nil?
        end

        def update_paperclip_settings
          Spree::Banner.attachment_definitions[ :attachment ][ :styles ]        = ActiveSupport::JSON.decode( Spree::Config[ :banner_styles ] ).symbolize_keys!
          Spree::Banner.attachment_definitions[ :attachment ][ :path ]          = Spree::Config[ :banner_path ]
          Spree::Banner.attachment_definitions[ :attachment ][ :default_url ]   = Spree::Config[ :banner_default_url ]
          Spree::Banner.attachment_definitions[ :attachment ][ :default_style ] = Spree::Config[ :banner_default_style ]
        end
    end
  end
end

app/views/spree/admin/banner_settings/edit.html.erb
<% content_for :page_title do %>
  <%= Spree.t( :banner_settings ) %>
<% end %>

<%= render partial: 'spree/admin/shared/configuration_menu' %>
<%= render partial: 'spree/admin/shared/banner_sub_menu' %>

<%= form_tag admin_banner_settings_path, method: :put do %>
  <% destroy = Spree.t( :destroy ) %> 

  <fieldset class="no-border-top">
    <fieldset class="no-border-bottom">
      <legend align="center"><%= Spree.t( :general_settings ) %></legend>

      <div class="field">
        <div class="warning note">
          <%= Spree.t( :banner_settings_warning ) %>
        </div>
      </div>    

      <div data-hook="attachment_path" class="field">
        <%= label_tag            'preferences[ banner_path ]', Spree.t( :banner_path ) %>
        <%= preference_field_tag 'preferences[ banner_path ]', Spree::Config[ :banner_path ], type: :string %>
      </div>

      <div class="alpha eight columns">
        <div data-hook="attachment_default_url" class="field">
          <%= label_tag            'preferences[ banner_default_url ]', Spree.t( :banner_default_url ) %>
          <%= preference_field_tag 'preferences[ banner_default_url ]', Spree::Config[ :banner_default_url ], type: :string %>
        </div>
      </div>

      <div class="alpha eight columns">
        <div data-hook="attachment_url" class="field">
          <%= label_tag            'preferences[ banner_url ]', Spree.t( :banner_url ) %>
          <%= preference_field_tag 'preferences[ banner_url ]', Spree::Config[ :banner_url ], type: :string %>
        </div>
      </div>

      <div class="omega four columns">
        <div data-hook="attachment_default_style" class="field">
          <%= label_tag         'preferences[ banner_default_style ]', Spree.t( :banner_default_style ) %>
          <%= collection_select 'preferences', 'banner_default_style', @styles, :first, :first, { selected: Spree::Config[ :banner_default_style ] }, class: 'select2 fullwidth' %> 
        </div>
      </div>
    </fieldset>

    <fieldset class="no-border-bottom" id="attachment_styles" data-hook="banner_styles">
      <legend align="center"><%= Spree.t( :banner_styles ) %></legend>

      <div id="styles_list" class="row frameless">      
        <% @styles.each_with_index do | ( style_name, style_value ), index | %>
          <div class="field three columns">
            <%= label_tag      "banner_styles[ #{ style_name } ]", style_name %>
            <a href='#' alt="<%= destroy %>" title="<%= destroy %>" class='destroy_style with-tip'><i class='icon-trash'></i></a>
            <%= text_field_tag "banner_styles[ #{ style_name } ]", style_value, class: 'fullwidth' %>
          </div>
        <% end %>
      </div>

      <div id="new-styles" class="row frameless"></div>

      <div class="field">
        <%= link_to_with_icon 'icon-plus', Spree.t( :add_new_banner_style ), '#', class: 'add_new_style button' %>
      </div>
    </fieldset>    

    <div class="form-buttons filter-actions actions" data-hook="buttons">
      <%= button Spree.t( :update ), 'icon-refresh' %>
    </div>
  </fieldset>
<% end %>